version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_USER: 'user'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'db'
      MYSQL_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./docker:/docker-entrypoint-initdb.d